// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3GCK--OD92EO027_5n0DW90kRSa2434',
    appId: '1:32715465370:web:9e1704d3c501780ea23523',
    messagingSenderId: '32715465370',
    projectId: 'assignmentapp-1648d',
    authDomain: 'assignmentapp-1648d.firebaseapp.com',
    storageBucket: 'assignmentapp-1648d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFEY2WIN3yzvE26X5JMMQ_IlqOxKp78w0',
    appId: '1:32715465370:android:2542cf0276399ae5a23523',
    messagingSenderId: '32715465370',
    projectId: 'assignmentapp-1648d',
    storageBucket: 'assignmentapp-1648d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOy61l3IwJH4nb-7LlOHfW3lf71A7efk',
    appId: '1:32715465370:ios:266c97c9ed6b2edfa23523',
    messagingSenderId: '32715465370',
    projectId: 'assignmentapp-1648d',
    storageBucket: 'assignmentapp-1648d.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlOy61l3IwJH4nb-7LlOHfW3lf71A7efk',
    appId: '1:32715465370:ios:266c97c9ed6b2edfa23523',
    messagingSenderId: '32715465370',
    projectId: 'assignmentapp-1648d',
    storageBucket: 'assignmentapp-1648d.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk3GCK--OD92EO027_5n0DW90kRSa2434',
    appId: '1:32715465370:web:588549fbd1e9e6dda23523',
    messagingSenderId: '32715465370',
    projectId: 'assignmentapp-1648d',
    authDomain: 'assignmentapp-1648d.firebaseapp.com',
    storageBucket: 'assignmentapp-1648d.firebasestorage.app',
  );
}
